http:
  host: "0.0.0.0"
  port: "8081"
  timeout: "15000"
  
papi: 
  host: "ntn-accounts-sf-jde-sync-papi-prod-xbmlkc.xryhvh.usa-e2.cloudhub.io"
  port: "443"
  method: "POST"
  path: "/accounts"  

  
#app name
app:
  name: "ntn-accounts-salesforce-jde-sync-eapi"  
  env: "PROD"  
  
smtp:
  host: "smtp.office365.com"
  port: "25"  
  to: "donotreply@ntnusa.com,ntnmule@prowesssoft.com"